
使用std::thread启动一个线程来计算单个结果，从线程中获取计算结果并不容易。另一个std::thread的问题是如何处理错误，例如异常。如果一个线程抛出一个异常，而这个异常没有捕获，C++运行时会调用std::terminate()，这通常会终止整个应用程序。

future可以用来更容易地从线程中获取结果，并将异常从一个线程传输到另一个线程，然后线程可以处理异常。

promise是线程存储其结果的地方，future用于获取存储在promise中的结果。promise是结果的输入端，future是结果的输出端。当函数（在同一线程或另一个线程中）计算出想要返回的值，就会将这个值放入一个promise中。这个值可以通过future检索，promise/future对是用于结果的线程间一次性通信通道。

C++提供了一个标准future，称为std::future。可以像以下方式从std::future中检索结果，T是计算结果的类型。

\begin{cpp}
future<T> myFuture { ... }; // Is discussed later.
T result { myFuture.get() };
\end{cpp}

调用get()检索结果，并将其存储在变量result中。如果计算结果还没有完成，调用get()会阻塞，直到值可用。只能在一个future上调用get()一次，标准中未定义再次调用get()的行为。

如果想避免阻塞，可以首先查询future是否有可用的结果：

\begin{cpp}
if (myFuture.wait_for(0)) { // Value is available.
    T result { myFuture.get() };
} else { // Value is not yet available.
    ...
}
\end{cpp}

\mySubsubsection{27.9.1}{std::promise 和 std::future}

C++提供了std::promise类作为实现promise的一种方式，可以调用set\_value()在promise中存储一个结果，或者调用set\_exception()在promise中存储一个异常。只能在特定的promise上调用set\_value()或set\_exception()一次。如果多次调用，会抛出一个std::future\_error异常。

可以使用set\_value\_at\_thread\_exit()或set\_exception\_at\_thread\_exit()在promise中设置一个值或一个异常。使用这些方法，值或异常在线程退出和所有线程局部存储变量销毁之后，存储在promise中。

一个线程A启动另一个线程B来计算某些内容时，可以创建一个promise并将其传递给启动的线程。不能复制promise，但可以移动到线程中！线程B使用该promise来存储结果。将promise移动到线程B之前，线程A调用get\_future()在创建的promise上，当B完成就可以访问结果。一个简单的示例：

\begin{cpp}
void doWork(promise<int> thePromise)
{
    // ... Do some work ...
    // And ultimately store the result in the promise.
    thePromise.set_value(42);
}

int main()
{
    // Create a promise to pass to the thread.
    promise<int> myPromise;
    // Get the future of the promise.
    auto theFuture { myPromise.get_future() };
    // Create a thread and move the promise into it.
    jthread theThread { doWork, move(myPromise) };

    // Do some more work...

    // Get the result.
    int result { theFuture.get() };
    println("Result: {}", result);
}
\end{cpp}

\begin{myNotic}{NOTE}
这段代码只是为了演示目的。在新的线程中启动计算，然后阻塞调用future的get()，直到结果计算出来。这听起来像是一个昂贵的函数调用。实际中，可以定期检查是否有可用结果（使用前面讨论的wait\_for()），或者使用同步机制，如条件变量。当结果尚未可用时，可以在等待的同时做其他事情，而不是阻塞。
\end{myNotic}

\mySubsubsection{27.9.2}{std::packaged\_task}

std::packaged\_task比显式使用std::promise（如前一节所示）更容易与承诺一起工作。以下代码创建了一个packaged\_task来执行calculateSum()，通过调用get\_future()从packaged\_task中获取future。创建了一个线程，并将packaged\_task移动到线程中。packaged\_task，就像std::promise一样，是可移动的。线程启动后，从检索到的future上阻塞调用get()以获取结果，直到结果可用。

calculateSum()没有显式地将内容存储在promise中。packaged\_task会自动创建一个promise，并自动将可调用对象的返回结果——calculateSum()的结果——存储在promise中，无论该结果是一个值，还是一个抛出的异常。

\begin{cpp}
int calculateSum(int a, int b) { return a + b; }

int main()
{
    // Create a packaged task to run calculateSum.
    packaged_task task { calculateSum };
    // Get the future for the result of the packaged task.
    auto theFuture { task.get_future() };
    // Create a thread, move the packaged task into it, and
    // execute the packaged task with the given arguments.
    jthread theThread { move(task), 39, 3 };

    // Do some more work...

    // Get the result.
    int result { theFuture.get() };
    println("Result: {}", result);
}
\end{cpp}

\mySubsubsection{27.9.3}{std::async}

如果想给C++运行时更多控制权，以决定是否创建一个线程来计算某事，可以使用std::async()。它接受一个可调用的对象来执行，并返回一个future，可以使用它来获取结果。async()可以通过两种方式执行一个可调用对象：

\begin{itemize}
\item
不同的线程上异步运行

\item
调用线程上同步运行，当返回的future上调用get()时
\end{itemize}

如果在没有参数的情况下调用async()，运行时会根据系统中的CPU核心数量和已经发生的并发量等因素自动选择两种机制之一。可以通过指定一个策略参数，来影响运行时的行为：

\begin{itemize}
\item
launch::async: 强制运行时在不同的线程上异步执行可调用对象。

\item
launch::deferred: 当调用get()时，强制运行时在调用线程上同步执行可调用对象。

\item
launch::async | launch::deferred: 让运行时自行选择（=默认行为）。
\end{itemize}

以下示例演示了async()的用法：

\begin{cpp}
int calculateSum(int a, int b) { return a + b; }

int main()
{
    auto myFuture { async(calculateSum, 39, 3) };
    //auto myFuture { async(launch::async, calculateSum, 39, 3) };
    //auto myFuture { async(launch::deferred, calculateSum, 39, 3) };

    // Do some more work...

    // Get the result.
    int result { myFuture.get() };
    println("Result: {}", result);
}
\end{cpp}

从这个代码段中可以看到，std::async()是最简单的方法，可以执行一些计算，无论是异步的（不同的线程上）还是同步的（同一个线程上），然后获取结果。

\begin{myWarning}{WARNING}
由async()调用返回的future在其析构函数中阻塞，直到结果可用。（这对于普通future不适用；只适用于从async()返回的那种。）如果调用async()而不捕获返回的future，async()调用实际上变成了一个阻塞调用！例如，以下行同步调用calculateSum()：

\begin{cpp}
async(calculateSum, 39, 3);
\end{cpp}

这条语句发生的情况是，async()创建并返回一个future。这个future没有捕获，所以是一个临时对象。因为这是一个临时future，所以在语句结束时调用其析构函数，并且这个析构函数会阻塞到结果可用。
\end{myWarning}

\mySubsubsection{27.9.4}{异常处理}

使用future的一个优点是，可以在线程之间传输异常。在future上调用get()，要么返回计算的结果，要么重新抛出存储在与之关联的promise中的异常。当使用packaged\_task或async()时，从启动的可调用对象中抛出的异常都会自动存储在promise中。如果直接使用std::promise，可以调用set\_exception()来存储一个异常。以下是使用async()的一个示例：

\begin{cpp}
int calculate()
{
    throw runtime_error { "Exception thrown from calculate()." };
}

int main()
{
    // Use the launch::async policy to force asynchronous execution.
    auto myFuture { async(launch::async, calculate) };

    // Do some more work...

    // Get the result.
    try {
        int result { myFuture.get() };
        println("Result: {}", result);
    } catch (const exception& ex) {
        println("Caught exception: {}", ex.what());
    }
}
\end{cpp}

\mySubsubsection{27.9.5}{std::shared\_future}

std::future<T>只需要T能够进行移动构造。当在future<T>上调用get()时，结果会从future中移动出来并返回，所以只能在一个future<T>上调用get()一次。

如果想多次调用get()时，甚至在多个线程中，需要使用std::shared\_future<T>。可以通过调用std::future::share()或通过将future传递给shared\_future构造函数来创建shared\_future。future是不可复制的，所以必须将其移动到shared\_future构造函数中。

shared\_future可以用来同时唤醒多个线程。以下代码定义了两个Lambda表达式，分别以不同的线程异步执行。每个Lambda表达式所做的第一件事就是将值设置为其各自的promise，以表明线程启动。然后阻塞调用get()在signalFuture上，直到通过future提供参数，之后继续执行。每个Lambda表达式都通过引用捕获了各自的promise，并通过值捕获了signalFuture，所以两个Lambda表达式都拥有signalFuture的副本。主线程使用async()以不同的线程异步执行这两个Lambda表达式，等待两个线程都开始，然后将参数设置在signalPromise中，这会唤醒两个线程。

\begin{cpp}
promise<void> thread1Started, thread2Started;

promise<int> signalPromise;
auto signalFuture { signalPromise.get_future().share() };
//shared_future<int> signalFuture { signalPromise.get_future() };

auto function1 { [&thread1Started, signalFuture] {
        thread1Started.set_value();
        // Wait until parameter is set.
        int parameter { signalFuture.get() };
        // ...
} };

auto function2 { [&thread2Started, signalFuture] {
        thread2Started.set_value();
        // Wait until parameter is set.
        int parameter { signalFuture.get() };
        // ...
} };

// Run both lambda expressions asynchronously.
// Remember to capture the future returned by async()!
auto result1 { async(launch::async, function1) };
auto result2 { async(launch::async, function2) };

// Wait until both threads have started.
thread1Started.get_future().wait();
thread2Started.get_future().wait();

// Both threads are now waiting for the parameter.
// Set the parameter to wake up both of them.
signalPromise.set_value(42);
\end{cpp}












