
调试程序可能会让人非常沮丧，采取系统化的方法会使这个过程变得容易得多。尝试调试程序时，第一步总是应该是重现错误。根据是否能够重现错误，后续方法会有所不同。接下来的四个部分解释了如何重现错误，如何调试可重现的错误，如何调试不可重现的错误，以及如何调试回归错误。其他部分解释了关于调试内存错误和调试多线程程序的细节，最后展示了一个逐步调试的示例。

\mySubsubsection{31.5.1}{重现错误}

如果能够重现错误，确定根本原因将变得更加容易。有时，错误可能由Alice重现，但Bob无法重现，这可能就是Alice找到根本原因的线索。如果错误无法重现，确定其根本原因可能非常困难，甚至是不可能的。

为了重现错误，首先在类似的环境（硬件、操作系统等）上运行程序，并使用与错误首次出现时相同的输入。确保包括从程序启动到出现错误时的所有输入，一个常见的错误是试图通过仅执行触发操作来重现错误。这种技术可能无法重现错误，因为错误可能由一系列完整的操作引起。

例如，网络浏览器在请求某个网页时崩溃，这可能是因为特定请求的网络地址触发了内存损坏。另一方面，可能是由于程序记录了所有请求，队列中有100万个条目空间，而这个条目是第1,000,001个。重新启动程序并发送一个请求在这种情况下肯定不会触发错误。

有时，可能无法模拟导致错误的整个事件序列。也许报告错误的人记不起她所做的所有事情。或者，程序运行了太长时间，无法模拟每一个输入。这时，尽力重现错误，需要一些猜测，可能会花费时间，但在这个阶段的投入将在调试过程中节省时间。以下是一些可以尝试的技术：

\begin{itemize}
\item
在正确的环境中重复触发操作，并尽可能多地输入与最初报告相似的输入。

\item
快速审查与错误相关的代码。会发现一个可能的原因，这有助于指导问题重现。

\item
运行自动化测试，以测试类似的功能。自动化测试的一个好处就是可以重现错误。如果需要24小时的测试才能出现错误，就让这些测试自行运行，比花费24小时试图重现错误要好。

\item
如果有必要的硬件，可以同时在不同机器上运行轻微变化的测试，这有时可以节省不少时间。

\item
运行压力测试，以测试类似的功能。如果程序是一个在特定请求时崩溃的网络服务器，并尝试同时运行尽可能多的浏览器。
\end{itemize}

当能够一致地重现错误，应该尝试找到最小的触发方式。可以从包含仅触发操作的最小方式开始，然后逐渐扩展，覆盖从启动到触发错误的整个过程。这将产生最简单、最有效的重现，这使得找到问题的根本原因变得更加简单，也更容易验证和修复问题。

\mySubsubsection{31.5.2}{调试可复现的错误}

当能够一致且高效地复现一个错误时，就该找出导致该错误的代码问题。此时目标是找到触发问题的确切代码行，可以使用两种不同的策略：

\begin{itemize}
\item
使用调试器：调试器允许逐步执行程序，并查看在各个点上的内存状态和变量值，通常是找到错误根本原因的不可或缺的工具。当能够访问源代码时，应该使用符号调试器：一种利用代码中的变量名、类名和其他符号的调试器。要使用符号调试器，必须指示编译器生成调试符号。查阅编译器的文档，了解如何启用符号生成的详细信息。

\item
记录调试消息：通过向程序中添加足够的调试消息，并在复现错误时观察其输出，应该能够精确定位错误发生的确切代码行。如果有调试器可用，通常不建议添加调试消息，这需要修改程序，可能会很耗时。如果已经像前面描述的那样用调试消息化了程序，可能会在复现错误时运行程序的调试模式来找到错误根本原因。有时仅仅是在启用日志记录时错误就会消失，启用日志记录的行为可能会改变应用程序的时序。
\end{itemize}

本章末尾的调试示例演示了这两种方法。

\mySubsubsection{31.5.3}{调试不可重现的错误}

修复不可重现的错误比修复可重现的错误要困难得多。通常没有多少信息，必须进行大量的猜测，但一些策略可供参考：

\begin{itemize}
\item
尝试将不可重现的错误转换为可重现的错误。通过使用有根据的猜测，通常可以确定错误的大致位置，花些时间尝试重现错误是值得的。当有了可重现的错误，就可以使用之前描述的技术来找出其根本原因。

\item
分析错误日志。如果按照之前所述在程序中加入了错误日志生成，这样做就很容易。应该仔细检查这些信息，在错误发生之前直接记录的错误，都可能对错误本身有所贡献。如果运气好（或者编写的程序很好），程序会记录出当前错误的确切原因。

\item
获取并分析跟踪信息，如果程序中加入了跟踪输出(通过前面提到的环形缓冲区)，这样做也很容易。错误发生时，最好能够获取到跟踪的副本，这些跟踪应该直接引导到代码中的错误位置。

\item
检查是否存在崩溃/内存转储文件，平台会自动生成应用程序异常终止时的内存转储文件。在Unix和Linux上，这些内存转储文件称为核心文件。每个平台都提供了用于分析这些内存转储的工具。可以用来查看应用程序的堆栈跟踪，及其在应用程序崩溃前的内存内容。

\item
检查代码。不幸的是，这往往是确定不可重现错误原因的唯一策略。令人惊讶的是，这通常有效。当检查代码时，即使是自己编写的代码，以刚刚发生的错误的角度去审视，通常也可以找到之前忽略的错误。我不建议花费数小时盯着代码看，但手动跟踪代码路径通常可以直接引导各位找到问题。

\item
使用内存监控工具，例如本章稍后部分“调试内存问题”中描述的工具。这类工具通常会提醒注意那些不一定导致程序行为异常，但可能是当前错误原因的内存错误。

\item
提交或更新一个错误报告。即使不能立即找到错误的根本原因，这个报告也将是记录您尝试过程的有用记录，如果问题再次出现，这将非常有用。

\item
如果无法找到错误的根本原因，请确保添加了日志或跟踪，以便下次错误发生时有机会找到原因。
\end{itemize}

当找到了不可重现错误的根本原因，应该创建一个可重现的测试用例，并将其归类到“可重现的错误”中。实际修复错误之前，能够重现错误非常重要。否则，将如何测试修复效果呢？调试不可重现的错误时，常见的错误是错误地修复了代码中的问题。由于无法重现错误，不知道是否真的修复了它。当一个月后它再次出现时，不应该为此感到惊讶。

\mySubsubsection{31.5.4}{调试回归错误}

如果一个功能包含了一个回归错误，则该功能以前是正常工作的，但在某个时刻意外地停止了工作。

调查回归错误的一种有用的调试技术是，查看相关文件的变化日志。如果知道功能最后一次正常工作的时间，查看从那时以来的所有变化日志。可能会注意到一些可疑的东西，这可能会有助于找到根本原因。

调试回归错误时，使用二分法搜索旧版本的软件（通常称为二分查找）可以节省大量时间，以尝试确定何时开始出错。如果保留了旧版本的二进制文件，可以使用它们，或者可以将源代码恢复到旧版本。当知道何时开始出错，检查那个时间点的变化日志看看有什么变化。这种方法只有在可以复现错误时才可能实现。

\mySubsubsection{31.5.5}{调试内存问题}

大多数灾难性的错误，如应用程序崩溃，都是由内存错误引起的。许多非灾难性的错误也是由内存错误触发的。一些内存错误是显而易见的，例如：程序尝试取消引用空指针，默认行为是终止程序。每个平台都允许对灾难性错误做出响应，并采取补救措施。对响应付出的努力取决于，这种恢复对最终用户的重要性。例如，文本编辑器真的需要尽最大努力保存修改过的缓冲区（可能是在“已恢复”的名称下），而对于其他程序，用户可能会认为默认行为是可以接受的，即使令人不快。

一些内存错误更加隐蔽。如果在C++中写过一个数组的末尾，程序可能不会在那个时候崩溃。如果该数组位于栈上，可能会写入一个不同的变量或数组，改变直到程序稍后才会出现的值。或者，数组位于堆区，可能会引起堆区的内存损坏，这会在尝试动态分配或释放更多内存时导致错误。

第7章从编码时应该避免什么的角度，介绍了常见的内存错误。本节从识别显示错误的代码中的问题的角度讨论内存错误。继续本节之前，应该了解第7章的内容。

\begin{myWarning}{WARNING}
使用智能指针，而不是原始指针，可以避免以下大多数（如果不是全部）内存问题。
\end{myWarning}

\mySamllsection{内存错误类别}

要调试内存问题，应该熟悉可能发生的错误类型。本节描述了主要的内存错误类别。每个类别列出不同类型的内存错误，包括演示每个错误的简短代码示例，以及可能会观察到的可能症状列表。症状并不等同于错误：症状是由错误引起的可观察行为。

\mySamllsection{内存释放错误}

以下表格总结了涉及内存释放的五种主要错误：

% Please add the following required packages to your document preamble:
% \usepackage{longtable}
% Note: It may be necessary to compile the document several times to get a multi-page table to line up properly
\begin{longtable}{|l|l|l|}
\hline
\textbf{错误类型} &
\textbf{症状} &
\textbf{示例} \\ \hline
\endfirsthead
%
\endhead
%
内存泄漏 &
\begin{tabular}[c]{@{}l@{}}进程内存使用随时间增长。\\进程随时间运行得更慢。\\最终，操作系统中的操作\\和系统调用会因内存不足\\而失败。\end{tabular} &
\begin{tabular}[c]{@{}l@{}}
\\
\begin{cpp}
void memoryLeak()
{
    int* p { new int[1000] };
    return; // Not freeing p!
}
\end{cpp}
\end{tabular}
\\ \hline
\begin{tabular}[c]{@{}l@{}}使用不匹配的\\分配和释放操\\作\end{tabular} &
\begin{tabular}[c]{@{}l@{}}通常不会立即导致崩溃。\\这种类型的错误可能在\\某些平台上导致内存损\\坏，也可能出现崩溃。\\某些不匹配也可能导致\\内存泄漏。\end{tabular} &
\begin{tabular}[c]{@{}l@{}}
\\
\begin{cpp}
void mismatchedFree()
{
    int* p1{(int*)malloc(sizeof(int))};
    int* p2{new int};
    int* p3{new int[1000]};
    delete p1; // Should use free()!
    delete[] p2;// Should use delete!
    free(p3); // Should use delete[]!
}
\end{cpp}
\end{tabular}
\\ \hline
\begin{tabular}[c]{@{}l@{}}多次释放内存\end{tabular} &
\begin{tabular}[c]{@{}l@{}}如果在两次调用delete之间\\的某个时刻，该内存已经被\\另一个分配操作占用，可能\\会导致崩溃。\end{tabular} &
\begin{tabular}[c]{@{}l@{}}
\\
\begin{cpp}
void doubleFree()
{
    int* p1 { new int[1000] };
    delete[] p1;
    int* p2 { new int[1000] };
    delete[] p1; // Freeing p1 twice!
} // Leaking memory of p2!
\end{cpp}
\end{tabular}
\\ \hline
\begin{tabular}[c]{@{}l@{}}释放未分配的\\内存\end{tabular} &
通常会导致崩溃。 &
\begin{tabular}[c]{@{}l@{}}
\\
\begin{cpp}
void freeUnallocated()
{
    int* p{reinterpret_cast<int*>(10)};
    delete p; // p not a valid pointer!
}
\end{cpp}
\end{tabular}
\\ \hline
\begin{tabular}[c]{@{}l@{}}释放栈内存\end{tabular} &
\begin{tabular}[c]{@{}l@{}}从技术上讲，这是释放未分\\配内存的一种特殊情况。通\\常会导致崩溃。\end{tabular} &
\begin{tabular}[c]{@{}l@{}}
\\
\begin{cpp}
void freeStack()
{
    int x;
    int* p { &x };
    delete p; // Freeing stack memory!
}
\end{cpp}
\end{tabular}
\\ \hline
\end{longtable}

表中提到的崩溃在不同平台上可能有不同的表现形式，例如：段错误、总线错误、访问违规等。

一些错误不会立即导致程序终止。这些错误更微妙，导致程序在执行过程中出现其他问题。

\mySamllsection{内存访问错误}

内存错误的一个类别涉及实际读写内存：

% Please add the following required packages to your document preamble:
% \usepackage{longtable}
% Note: It may be necessary to compile the document several times to get a multi-page table to line up properly
\begin{longtable}{|l|l|l|}
\hline
\textbf{错误类型} &
\textbf{症状} &
\textbf{示例} \\ \hline
\endfirsthead
%
\endhead
%
\begin{tabular}[c]{@{}l@{}}访问无效内存\end{tabular} &
\begin{tabular}[c]{@{}l@{}}导致程序立即崩溃。\end{tabular} &
\begin{tabular}[c]{@{}l@{}}
\\
\begin{cpp}
void accessInvalid()
{
    int* p {reinterpret_cast<int*>(10)};
    *p = 5; // p is not a valid pointer!
}
\end{cpp}
\end{tabular} \\ \hline
\begin{tabular}[c]{@{}l@{}}访问已释放内\\存\end{tabular} &
\begin{tabular}[c]{@{}l@{}}通常不会导致崩溃。\\如果内存已分配给\\其他对象，此错误\\类型可能会导致\\“奇怪”且潜在危险\\的值出现。\end{tabular} &
\begin{tabular}[c]{@{}l@{}}
\\
\begin{cpp}
void accessFreed()
{
    int* p1 { new int };
    delete p1;
    *p1 = 5; // The memory pointed to
             // by p1 has been freed!
}
\end{cpp}
\end{tabular} \\ \hline
\begin{tabular}[c]{@{}l@{}}访问不同分配\\的内存\end{tabular} &
\begin{tabular}[c]{@{}l@{}}通常不会导致崩溃。\\此错误类型可能会\\导致其他变量或临\\时对象中意外出现\\“奇怪”且潜在危险\\的值，甚至改变程\\序的控制流。\end{tabular} &
\begin{tabular}[c]{@{}l@{}}
\\
\begin{cpp}
void accessElsewhere()
{
    int x, y[10], z;
    x = 0;
    z = 0;
    for (int i { 0 }; i <= 10; ++i) {
        y[i] = 5; // BUG for i==10! element
        // 10 is past end of array
    }
}
\end{cpp}
\end{tabular} \\ \hline
\begin{tabular}[c]{@{}l@{}}读取未初始化\\的内存\end{tabular} &
\begin{tabular}[c]{@{}l@{}}不会导致崩溃，除非\\将未初始化的值作为\\指针或数组索引并取\\消引用（如示例所示）\\。即使在这种情况下，\\也不一定会导致崩溃。\end{tabular} &
\begin{tabular}[c]{@{}l@{}}
\\
\begin{cpp}
void readUninitialized()
{
    int* p;
    print("{}",*p);// p is uninitialized!
}
\end{cpp}
\end{tabular} \\ \hline
\end{longtable}

内存访问错误并不总是导致崩溃，它们可能导致微妙的错误，程序不会终止，而是产生错误的输出。错误的输出可能导致严重后果，当外部设备（如机械臂、X射线机、放射治疗、生命支持系统等）由计算机控制时。

这里讨论的内存释放和内存访问错误的症状是，程序的发布版本的症状。调试版本的行为可能会有所不同，当在调试器中运行程序时，调试器可能会在错误发生时中断代码的执行。

\mySamllsection{调试内存错误的小贴士}

与内存相关的错误通常每次运行程序时，都会在代码的不同位置出现。这通常与堆损坏有关。堆内存损坏就像一个定时炸弹，准备在尝试在堆上分配、释放或使用内存时爆炸。如果看到一个可重现但每次出现位置略有不同的错误，应该怀疑是内存损坏。

如果怀疑有内存错误，最好的选择是使用C++的内存检查工具。调试器通常提供运行时检查内存错误的选项。如果在Microsoft Visual C++调试器中运行应用程序的调试构建，将捕获前述各节中讨论的几乎所有类型的错误。还有一些优秀的第三方工具，如Rational Software（现由IBM拥有）的Purify和Linux上的Valgrind（在第7章中讨论）。Microsoft还提供了一个名为Application Verifier的免费下载（Windows SDK的一部分，\url{https://developer.microsoft.com/windows/downloads/windows-sdk}），可以在Windows环境中与应用程序的发布构建一起使用，是一个运行时验证工具，可协助找到之前讨论的微妙的编程错误，如内存错误。这些调试器和工具通过插入自己的内存分配和释放例程来检查动态内存的误用，例如：释放未分配的内存、引用未分配的内存或写入数组的末尾。

如果没有内存检查工具可用，且常规调试策略不起作用，可能需要求助于代码审查。首先，缩小包含错误的代码部分。然后，查看所有原始指针。假设质量中等到良好的代码上工作，大多数指针都应该已经用智能指针封装。如果确实遇到了原始指针，请仔细查看它们的使用方式，因为它们可能是错误的原因。

\mySamllsection{对象和类相关的错误}

\begin{itemize}
\item
验证具有动态分配内存的类是否有析构函数，该析构函数恰好释放对象中分配的内存：不多也不少。

\item
确保类正确处理复制和赋值，使用复制构造函数和赋值操作符，如第9章中所述。确保移动构造函数和移动赋值操作符正确地将源对象中的指针设置为nullptr，以便其析构函数不尝试释放该内存。

\item
检查可疑的强制类型转换。如果将一个类型的指针转换为另一个类型的对象指针，请确保其有效性，请使用dynamic\_cast。
\end{itemize}

\begin{myWarning}{WARNING}
无论何时看到原始指针用来处理资源的所有权，我都强烈建议用智能指针替换这些原始指针，并尝试重构类型，以遵循第9章中讨论的零规则。这消除了前面列表中第一和第二个项解释的错误原因。
\end{myWarning}

\mySamllsection{通用内存错误}

\begin{itemize}
\item
确保每个调用new都有一个delete与之匹配，每个调用new[]都有一个delete[]与之匹配。同样，每个调用malloc、alloc或calloc都应该有一个free与之匹配。为了避免多次释放内存或使用已释放的内存，建议在释放内存后将其指针设置为nullptr。当然，最好的解决方案是简单地避免使用原始指针来处理资源的所有权，而是使用智能指针。

\item
检查缓冲区溢出。每当遍历数组或向C风格字符串写入或从中读取时，请验证是否未访问数组或字符串之外的内存。这些问题通常可以通过使用标准库容器和字符串来避免。

\item
检查对无效指针的解引用。

\item
在栈上声明指针（或任何标量类型）时，请确保声明时始终对其进行初始化。例如，使用T* p\{nullptr\};或T* p\{new T\};，但绝不要使用T* p;。最好使用智能指针！

\item
类似地，确保类在类初始化器或构造函数中始终初始化指针数据成员，通过在构造函数中分配内存或设置指针为nullptr。这里，使用智能指针也是最佳解决方案。
\end{itemize}


\mySubsubsection{31.5.6}{调试多线程程序}

C++包括一个线程库，提供了线程和线程之间的同步机制。多线程的C++程序很常见，考虑调试多线程程序中涉及的特别问题很重要。多线程程序中的错误往往是由操作系统调度的时间变化引起的，并且难以复现，所以调试多线程程序需要一套特殊的技巧：

\begin{itemize}
\item
使用调试器：调试器使诊断某些多线程问题相对容易，例如：死锁。当出现死锁时，进入调试器并检查不同的线程。将能够看到哪些线程阻塞，以及在代码中的哪一行阻塞。结合显示可，以进入死锁情况的跟踪日志，应该足以修复死锁。

\item
使用基于日志的调试：调试多线程程序时，基于日志的调试有时比使用调试器调试某些问题更有效。可以在关键部分前后向程序添加日志语句，以及在获取和释放锁之前。基于日志的调试在调查竞争条件时非常有用。但添加日志语句会稍微改变运行时的时序，这可能会隐藏错误。

\item
插入强制睡眠和上下文切换：如果难以一致地复现一个问题，或者对根本原因有怀疑，但想验证它，可以通过使线程在特定时间睡眠来强制某些线程调度行为。<thread>定义了std::this\_thread命名空间中的sleep\_until()和sleep\_for()，可以使用它们来进行休眠，休眠时间可指定为std::time\_point或std::duration。在释放锁、信号条件变量或直接访问共享数据之前，使线程睡眠几秒钟可以揭示其他情况下可能未检测到的竞争条件。如果这种调试技术揭示了根本原因，则必须修复，以确保在删除这些强制睡眠和上下文切换后，仍然可以正确工作。永远不要将这些强制睡眠和上下文切换留在代码中！那将是错误地“修复”问题。

\item
进行代码审查：审查线程同步代码通常有助于发现和修复竞争条件。尝试一遍又一遍地证明发生的事情是不可能的，直到看到它是如何发生的。代码注释中写下这些“证明”，不会有任何伤害。此外，要求同事进行结对调试；她可能会看到你忽视的东西。
\end{itemize}

\mySubsubsection{31.5.7}{调试示例：文章引用}

本节展示了一个有错误的程序，并演示如何调试并修复问题。

假设编写一个允许用户搜索引用特定论文的研究文章的网页团队的一员，这种服务对于试图找到与自己作品相似的作者非常有用。当他们找到一个代表相关工作的论文，就可以寻找引用该论文的所有论文，以找到其他相关作品。

这个项目中，您负责从文本文件中读取原始引用数据。为了简化，假设每个论文的引用信息都在自己的文件中。此外，每个文件的第一行包含论文的作者、标题和出版信息；第二行总是空的；所有后续行包含文章的引用（每行一个）。以下是计算机科学中最重要的一篇论文的示例文件：

\begin{shell}
Alan Turing, "On Computable Numbers, with an Application to the
Entscheidungsproblem", Proceedings of the London Mathematical Society, Series 2,
Vol.42 (1936-37), 230-265.

Gödel, "Über formal unentscheidbare Sätze der Principia Mathematica und verwandter
Systeme, I", Monatshefte Math. Phys., 38 (1931), 173-198.
Alonzo Church. "An unsolvable problem of elementary number theory", American J. of
Math., 58 (1936), 345-363.
Alonzo Church. "A note on the Entscheidungsproblem", J. of Symbolic Logic, 1
(1936), 40-41.
E.W. Hobson, "Theory of functions of a real variable (2nd ed., 1921)", 87-88.
\end{shell}

\mySamllsection{ArticleCitations类的错误实现}

您可能决定通过编写一个ArticleCitations类来组织程序，该类从文件中读取信息并存储信息。这个类将第一行的文章信息存储在一个字符串中，并将引用存储在一个C风格的字符串数组中。

\begin{myWarning}{WARNING}
使用C风格数组的决定显然是错误的！应该选择一个标准库容器来存储引用。这里仅用作内存问题的演示。这个实现的另一个明显问题是，没有使用复制和交换模式（参见第9章）来实现赋值操作符。但这里只是为了演示有错误的应用程序。
\end{myWarning}

ArticleCitations类的定义，在article\_citations模块中：

\begin{cpp}
export class ArticleCitations
{
    public:
        explicit ArticleCitations(const std::string& filename);
        virtual ~ArticleCitations();
        ArticleCitations(const ArticleCitations& src);
        ArticleCitations& operator=(const ArticleCitations& rhs);

        const std::string& getArticle() const;
        int getNumCitations() const;
        const std::string& getCitation(int i) const;
    private:
        void readFile(const std::string& filename);
        void copy(const ArticleCitations& src);

        std::string m_article;
        std::string* m_citations { nullptr };
        int m_numCitations { 0 };
};
\end{cpp}

实现如下:(这个程序是有错误的！不要直接使用它或将其作为参考。)

\begin{cpp}
ArticleCitations::ArticleCitations(const string& filename)
{
    // All we have to do is read the file.
    readFile(filename);
}

ArticleCitations::ArticleCitations(const ArticleCitations& src)
{
    copy(src);
}

ArticleCitations& ArticleCitations::operator=(const ArticleCitations& rhs)
{
    // Check for self-assignment.
    if (this == &rhs) {
        return *this;
    }
    // Free the old memory.
    delete [] m_citations;
    // Copy the data.
    copy(rhs);
    return *this;
}

void ArticleCitations::copy(const ArticleCitations& src)
{
    // Copy the article name, author, etc.
    m_article = src.m_article;
    // Copy the number of citations.
    m_numCitations = src.m_numCitations;
    // Allocate an array of the correct size.
    m_citations = new string[m_numCitations];
    // Copy each element of the array.
    for (int i { 0 }; i < m_numCitations; ++i) {
        m_citations[i] = src.m_citations[i];
    }
}

ArticleCitations::~ArticleCitations()
{
    delete [] m_citations;
}

void ArticleCitations::readFile(const string& filename)
{
    // Open the file and check for failure.
    ifstream inputFile { filename };
    if (inputFile.fail()) {
        throw invalid_argument { "Unable to open file" };
    }
    // Read the article author, title, etc. line.
    getline(inputFile, m_article);

    // Skip the whitespace before the citations start.
    inputFile >> ws;

    int count { 0 };
    // Save the current position so we can return to it.
    streampos citationsStart { inputFile.tellg() };
    // First count the number of citations.
    while (!inputFile.eof()) {
        // Skip whitespace before the next entry.
        inputFile >> ws;
        string temp;
        getline(inputFile, temp);
        if (!temp.empty()) {
            ++count;
        }
    }

    if (count != 0) {
        // Allocate an array of strings to store the citations.
        m_citations = new string[count];
        m_numCitations = count;
        // Seek back to the start of the citations.
        inputFile.seekg(citationsStart);
        // Read each citation and store it in the new array.
        for (count = 0; count < m_numCitations; ++count) {
            string temp;
            getline(inputFile, temp);
            if (!temp.empty()) {
                m_citations[count] = temp;
            }
        }
    } else {
        m_numCitations = -1;
    }
}

const string& ArticleCitations::getArticle() const { return m_article; }

int ArticleCitations::getNumCitations() const { return m_numCitations; }

const string& ArticleCitations::getCitation(int i) const { return m_citations[i]; }
\end{cpp}

\mySamllsection{测试ArticleCitations类}

以下程序要求用户输入一个文件名，为该文件构造一个ArticleCitations实例，并将这个实例值传递给processCitations()函数，该函数打印出所有信息。这个有问题的示例中，通过值传递实例到函数是为了测试目的。

\begin{cpp}
void processCitations(ArticleCitations cit)
{
    println("{}", cit.getArticle());
    for (int i { 0 }; i < cit.getNumCitations(); ++i) {
        println("{}", cit.getCitation(i));
    }
}

int main()
{
    while (true) {
        print("Enter a file name (\"STOP\" to stop): ");
        string filename;
        cin >> filename;
        if (filename == "STOP") { break; }
        ArticleCitations cit { filename };
        processCitations(cit);
    }
}
\end{cpp}

决定在名为paper1.txt的文件上测试程序，该文件包含Alan Turing的示例。以下是输出结果：

\begin{shell}
Enter a file name ("STOP" to stop): paper1.txt
Alan Turing, "On Computable Numbers, with an Application to the
Entscheidungsproblem", Proceedings of the London Mathematical Society, Series 2,
Vol.42 (1936-37), 230-265.
[ 4 empty lines omitted for brevity ]
Enter a file name ("STOP" to stop): STOP
\end{shell}

这看起来不太对。应该打印出四个引用而不是四个空行。

\mySamllsection{基于消息的调试}

对于这个错误，决定尝试基于日志的调试。这是一个控制台应用程序，可以使用println()打印消息。这时，从读取引用的文件函数开始有意义。如果这个函数没有正确工作，那么显然对象不会有引用。修改readFile()如下所示：

\begin{cpp}
void ArticleCitations::readFile(const string& filename)
{
    // Code omitted for brevity.
    // First count the number of citations.
    println("readFile(): counting number of citations");
    while (!inputFile.eof()) {
        // Skip whitespace before the next entry.
        inputFile >> ws;
        string temp;
        getline(inputFile, temp);
        if (!temp.empty()) {
            println("Citation {}: {}", count, temp);
            ++count;
        }
        }
        println("Found {} citations", count);
        println("readFile(): reading citations");
        if (count != 0) {
        // Allocate an array of strings to store the citations.
        m_citations = new string[count];
        m_numCitations = count;
        // Seek back to the start of the citations.
        inputFile.seekg(citationsStart);
        // Read each citation and store it in the new array.
        for (count = 0; count < m_numCitations; ++count) {
            string temp;
            getline(inputFile, temp);
            if (!temp.empty()) {
                println("{}", temp);
                m_citations[count] = temp;
            }
        }
    } else {
        m_numCitations = -1;
    }
    println("readFile(): finished");
}
\end{cpp}

用这个程序运行相同的测试会得到以下输出:

\begin{shell}
Enter a file name ("STOP" to stop): paper1.txt
readFile(): counting number of citations
Citation 0: Gödel, "Über formal unentscheidbare Sätze der Principia Mathematica und
verwandter Systeme, I", Monatshefte Math. Phys., 38 (1931), 173-198.
Citation 1: Alonzo Church. "An unsolvable problem of elementary number theory",
American J. of Math., 58 (1936), 345-363.
Citation 2: Alonzo Church. "A note on the Entscheidungsproblem", J. of Symbolic
Logic, 1 (1936), 40-41.
Citation 3: E.W. Hobson, "Theory of functions of a real variable (2nd ed.,
1921)", 87-88.
Found 4 citations
readFile(): reading citations
readFile(): finished
Alan Turing, "On Computable Numbers, with an Application to the
Entscheidungsproblem", Proceedings of the London Mathematical Society, Series 2,
Vol.42 (1936-37), 230-265.
[ 4 empty lines omitted for brevity ]
Enter a file name ("STOP" to stop): STOP
\end{shell}

从输出中可以看到，程序第一次从文件中读取引用数时，正确地读取了它们。，第二次，读错了，在“readFile(): reading citation”和“readFile(): finished”之间没有打印任何内容——为什么呢?深入研究这个问题的一种方法是添加一些调试代码，来检查每次尝试读取引用后文件流的状态:

\begin{cpp}
void printStreamState(const istream& inputStream)
{
    if (inputStream.good()) { println("stream state is good"); }
    if (inputStream.bad()) { println("stream state is bad"); }
    if (inputStream.fail()) { println("stream state is fail"); }
    if (inputStream.eof()) { println("stream state is eof"); }
}

void ArticleCitations::readFile(const string& filename)
{
    // Code omitted for brevity.

    // First count the number of citations.
    println("readFile(): counting number of citations");
    while (!inputFile.eof()) {
        // Skip whitespace before the next entry.
        inputFile >> ws;
        printStreamState(inputFile);
        string temp;
        getline(inputFile, temp);
        printStreamState(inputFile);
        if (!temp.empty()) {
            println("Citation {}: {}", count, temp);
            ++count;
        }
    }

    println("Found {} citations", count);
    println("readFile(): reading citations");
    if (count != 0) {
        // Allocate an array of strings to store the citations.
        m_citations = new string[count];
        m_numCitations = count;
        // Seek back to the start of the citations.
        inputFile.seekg(citationsStart);
        // Read each citation and store it in the new array.
        for (count = 0; count < m_numCitations; ++count) {
            string temp;
            getline(inputFile, temp);
            printStreamState(inputFile);
            if (!temp.empty()) {
                println("{}", temp);
                m_citations[count] = temp;
            }
        }
    } else {
        m_numCitations = -1;
    }
    println("readFile(): finished");
}
\end{cpp}

当这次运行程序时，会发现一些有趣的信息:

\begin{shell}
Enter a file name ("STOP" to stop): paper1.txt
readFile(): counting number of citations
stream state is good
stream state is good
Citation 0: Gödel, "Über formal unentscheidbare Sätze der Principia Mathematica und
verwandter Systeme, I", Monatshefte Math. Phys., 38 (1931), 173-198.
stream state is good
stream state is good
Citation 1: Alonzo Church. "An unsolvable problem of elementary number theory",
American J. of Math., 58 (1936), 345-363.
stream state is good
stream state is good
Citation 2: Alonzo Church. "A note on the Entscheidungsproblem", J. of Symbolic
Logic, 1 (1936), 40-41.
stream state is good
stream state is good
Citation 3: E.W. Hobson, "Theory of functions of a real variable (2nd ed.,
1921)", 87-88.
stream state is eof
stream state is fail
stream state is eof
Found 4 citations
readFile(): reading citations
stream state is fail
stream state is fail
stream state is fail
stream state is fail
readFile(): finished
Alan Turing, "On Computable Numbers, with an Application to the
Entscheidungsproblem", Proceedings of the London Mathematical Society, Series 2,
Vol.42 (1936-37), 230-265.
[ 4 empty lines omitted for brevity ]
Enter a file name ("STOP" to stop): STOP
\end{shell}

看起来流的状态在第一次读取最后一个引用之后是良好的。因为paper1.txt文件包含一个空的最后一行，所以while循环在读取最后一个引用后还会执行一次。最后一次循环中，inputFile >{}> ws读取了最后一行中的空白字符，这导致流状态变为eof。代码仍然尝试使用getline()读取一行，这导致流状态变为fail和eof，这是符合预期。但在第二次尝试读取引用时，流状态仍然保持为fail，这看起来不太合理：在第二次读取引用之前，代码使用seekg()将流定位回引用的开始。

流在明确清除它们之前会保持其错误状态；seekg()不会自动清除fail状态。当流处于错误状态时，无法正确读取数据，这解释了为什么在第二次尝试读取引用后流状态仍然为fail。

仔细查看代码后发现，在到达文件末尾后，没有在istream上调用clear()。如果修改代码，并添加一个clear()调用，将能够正确读取引用。

以下是修改后的readFile()实现，不包括调试打印语句：

\begin{cpp}
void ArticleCitations::readFile(const string& filename)
{
    // Code omitted for brevity.

    if (count != 0) {
        // Allocate an array of strings to store the citations.
        m_citations = new string[count];
        m_numCitations = count;
        // Clear the stream state.
        inputFile.clear();
        // Seek back to the start of the citations.
        inputFile.seekg(citationsStart);
        // Read each citation and store it in the new array.
        for (count = 0; count < m_numCitations; ++count) {
            string temp;
            getline(inputFile, temp);
            if (!temp.empty()) {
                m_citations[count] = temp;
            }
        }
    } else {
        m_numCitations = -1;
    }
}
\end{cpp}

再次运行相同的测试在paper1.txt文件上现在显示了正确的四个引用。

\mySamllsection{在Linux上使用GDB调试器}

现在ArticleCitations类在一份引文文件上似乎运行良好，决定勇往直前，开始测试一些特殊情况，从一份没有引用的文件开始。该文件如下所示，并存储在名为paper2.txt的文件中：

\begin{shell}
Author with no citations
\end{shell}

当尝试在这个文件上运行程序时，根据Linux版本和编译器，可能会遇到类似于以下信息的崩溃：

\begin{shell}
Enter a file name ("STOP" to stop): paper2.txt
terminate called after throwing an instance of 'std::bad_alloc'
    what(): std::bad_alloc
Aborted (core dumped)
\end{shell}

“core dumped”意味着程序崩溃了，这次决定尝试调试器。GNU调试器（GDB）在Unix和Linux平台上广泛可用。首先，必须使用调试信息（-g与g++）编译程序，再使用GDB启动程序。以下是使用调试器找到此问题的根本原因的示例会话，这个例子假设编译的可执行文件称为buggyprogram。

\begin{shell}
> gdb buggyprogram
[ Start-up messages omitted for brevity ]
Reading symbols from /home/marc/c++/gdb/buggyprogram...done.
(gdb) run
Starting program: buggyprogram
Enter a file name ("STOP" to stop): paper2.txt
terminate called after throwing an instance of 'std::bad_alloc'
    what(): std::bad_alloc
Program received signal SIGABRT, Aborted.
0x00007ffff7535c39 in raise () from /lib64/libc.so.6
(gdb)
\end{shell}

当程序崩溃时，调试器会中断执行，并允许在那个时间点探索程序的状态。backtrace或bt命令显示当前的堆栈跟踪。最后操作位于顶部，帧编号为零（\#0）。

\begin{shell}
gdb) bt
#0 0x00007ffff7535c39 in raise () from /lib64/libc.so.6
#1 0x00007ffff7537348 in abort () from /lib64/libc.so.6
#2 0x00007ffff7b35f85 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/
libstdc++.so.6
#3 0x00007ffff7b33ee6 in ?? () from /lib64/libstdc++.so.6
#4 0x00007ffff7b33f13 in std::terminate() () from /lib64/libstdc++.so.6
#5 0x00007ffff7b3413f in __cxa_throw () from /lib64/libstdc++.so.6
#6 0x00007ffff7b346cd in operator new(unsigned long) () from /lib64/libstdc++.so.6
#7 0x00007ffff7b34769 in operator new[](unsigned long) () from /lib64/
libstdc++.so.6
#8 0x00000000004016ea in ArticleCitations::copy (this=0x7fffffffe090, src=...) at
ArticleCitations.cpp:39
#9 0x00000000004015b5 in ArticleCitations::ArticleCitations
(this=0x7fffffffe090, src=...)
    at ArticleCitations.cpp:15
#10 0x0000000000401d0c in main () at ArticleCitationsTest.cpp:23
\end{shell}

当得到这样的堆栈跟踪时，应该尝试找到顶部第一个来自自己的代码的堆栈帧。这个例子中，这是堆栈帧\#8。从这帧中，可以看到似乎ArticleCitations类的copy()成员函数有问题。这个成员函数被调用是因为main()调用processCitations()，并将参数按值传递，这触发了复制构造函数的调用，从而调用了copy()。生产代码中，应该传递常量引用，但在这个有问题的程序示例中使用了按值传递。可以使用frame命令将调试器切换到堆栈帧\#8，这需要想要跳转到的帧的索引：

\begin{cpp}
(gdb) frame 8
#8 0x00000000004016ea in ArticleCitations::copy (this=0x7fffffffe090, src=...) at
ArticleCitations.cpp:39
39   m_citations = new string[m_numCitations];
\end{cpp}

这表明以下行出了问题：

\begin{cpp}
m_citations = new string[m_numCitations];
\end{cpp}

现在，可以使用list命令显示当前堆栈帧中与错误行附近的代码：

\begin{shell}
(gdb) list
34      // Copy the article name, author, etc.
35      m_article = src.m_article;
36      // Copy the number of citations.
37      m_numCitations = src.m_numCitations;
38      // Allocate an array of the correct size.
39      m_citations = new string[m_numCitations];
40      // Copy each element of the array.
41      for (int i { 0 }; i < m_numCitations; ++i) {
42          m_citations[i] = src.m_citations[i];
43      }
\end{shell}

在GDB中，可以使用print命令打印当前作用域中可用的值。为了找到问题的根本原因，可以尝试打印一些变量。错误发生在copy()成员函数内部，所以先来检查src参数的值：

\begin{shell}
(gdb) print src
$1 = (const ArticleCitations &) @0x7fffffffe060: {
    _vptr.ArticleCitations = 0x401fb0 <vtable for ArticleCitations+16>,
    m_article = "Author with no citations", m_citations = 0x000000000000,
    m_numCitations = -1}
\end{shell}

啊哈！这就是问题所在。这篇文章不应该有任何引用，为什么m\_numCitations设置为奇怪的值-1？再看看readFile()代码中没有引用的情况。这时，m\_numCitations错误地设置为-1。修复方法很简单：需要将m\_numCitations初始化为0，而不是在没有引用时，将其设置为-1。另一个问题是readFile()可以多次调用同一个ArticleCitations对象，所以还需要释放之前分配的m\_citations数组。以下是修复后的代码：

\begin{cpp}
void ArticleCitations::readFile(const string& filename)
{
    // Code omitted for brevity.

    delete [] m_citations; // Free previously allocated citations.
    m_citations = nullptr;
    m_numCitations = 0;
    if (count != 0) {
        // Allocate an array of strings to store the citations.
        m_citations = new string[count];
        m_numCitations = count;

        // Code omitted for brevity.
    }
}
\end{cpp}

正如这个例子所示，bug并不总是立即显现。通常需要调试器和一些坚持，才能找到它们。

\mySamllsection{使用Visual C++ 2022调试器}

本节解释了与上一节相同但使用Microsoft Visual C++ 2022调试器，而不是GDB的调试过程。

首先，需要创建一个项目。在Visual Studio 2022的欢迎屏幕上点击“新建项目”按钮，或者选择“文件" $\rightarrow$ “新建" $\rightarrow$ “项目"。在“创建新项目”对话框中，搜索带有C++、Windows和控制台标签的控制台应用程序项目模板，然后点击“下一步”。输入ArticleCitations作为项目的名称，选择一个保存项目的文件夹，然后点击“创建”。项目创建完成，可以在解决方案资源管理器中看到项目文件列表。如果这个停靠窗口不可见，请选择“视图" $\rightarrow$ “解决方案资源管理器"。项目将已经包含一个名为ArticleCitations.cpp的文件，列在解决方案资源管理器树中的源文件下。在解决方案资源管理器中选择这个文件，然后删除它，添加自己的文件。

现在添加我们的文件。在解决方案资源管理器中右键点击ArticleCitations项目，然后选择“添加” $\rightarrow$ “现有项”。将本书源码库中06\_ArticleCitations\verb|\|04\_AfterLogDebugging文件夹中的所有文件添加到项目中。现在的解决方案资源管理器应该类似于图31.1。

\myGraphic{0.5}{content/part5/chapter31/images/1.png}{图 31.1}

这个示例使用了C++23特性，在Visual C++ 2022中目前还没有默认启用。要启用它们，请在解决方案资源管理器窗口中右键点击ArticleCitations项目，然后点击属性。在属性窗口中，选择“配置属性” $\rightarrow$ “常规”，并将C++语言标准选项设置为“ISO C++23标准”或“预览 - 来自最新C++工作草案的功能”，这取决于Visual C++的版本。ISO C++23标准选项目前还没有，但将在Visual C++的未来更新中出现。在属性窗口中，“转到配置属性” $\rightarrow$ “C/C++” $\rightarrow$ “命令行”，并添加/utf-8作为附加选项。这将确保诸如Gödel中的ö这样的字符能正确打印。

确保配置设置为调试而不是发布，然后通过选择“构建” $\rightarrow$ “构建解决方案”来编译整个程序。然后将paper1.txt和paper2.txt测试文件复制到ArticleCitations项目的文件夹中，这个文件夹包含ArticleCitations.vcxproj文件。

通过选择“调试” $\rightarrow$ “开始调试”来运行应用程序。首先指定paper1.txt文件。应该正确读取文件并输出结果到控制台，再测试paper2.txt。调试器会中断执行，显示一个类似于图31.2的消息。

\myGraphic{0.7}{content/part5/chapter31/images/2.png}{图 31.2}

这表明抛出了std::bad\_array\_new\_length异常。如果看到的代码不是自己编写的代码，那么需要找到自己代码中导致异常的行。要做到这一点，请使用调用堆栈窗口（“调试” $\rightarrow$ “窗口” $\rightarrow$ “调用堆栈”）。在调用堆栈中，需要找到第一个包含自己编写的代码的行。如图31.3所示。可以双击调用堆栈窗口中的行，跳转到代码中的那一行。

\myGraphic{0.7}{content/part5/chapter31/images/3.png}{图 31.3}

正如GDB示例中所见，问题在ArticleCitations::copy()中。

现在可以简单地将鼠标悬停在变量名上以检查其值。如果悬停在src上，会注意到m\_numCitations是-1。原因和修复方法与GDB示例相同。

除了悬停在变量上以检查它们的值之外，还可以使用“调试” $\rightarrow$ “窗口” $\rightarrow$ “自动窗口”，它显示了一个变量列表。图31.4显示了这个列表，其中src变量展开以显示其数据成员。从这个窗口，还可以看到m\_numCitations是-1。

\myGraphic{0.7}{content/part5/chapter31/images/4.png}{图 31.4}

\mySubsubsection{31.5.8}{从ArticleCitations示例中学到的教训}

有的读者可能会认为这个示例太小，不足以代表真实的调试工作。尽管有错误的代码并不长，但编写的许多类在大型项目中也不会大多少。想象一下，如果将这个示例与项目的其他部分集成之前没有彻底测试它，如果这些错误后来出现，你和其它工程师将花费更多时间来缩小问题范围，才能像这里展示的那样进行调试。此外，这个示例中展示的技术适用于所有调试工作，无论规模大小。














